#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_table_4_1.py

Purpose
-------
Generate Table 4.1: Distribution of Error Types and Mean Homogenization Scores.

Table 4.1 was generated by grouping the 100 error units by error type and
calculating the mean semantic and lexical homogenization scores for each category.
Semantic homogenization was calculated as the average BERTScore F1 across the
three pairwise model comparisons, while lexical homogenization was calculated as
the average Jaccard Similarity across the same three model pairs.

Expected input
--------------
A detailed quantitative results CSV file, normally produced by the full
BERTScore + Jaccard analysis script.

The input file should contain at least the following columns:

    unit_id
    error_type
    bertscore_gpt_deepseek
    bertscore_gpt_gemini
    bertscore_deepseek_gemini
    jaccard_gpt_deepseek
    jaccard_gpt_gemini
    jaccard_deepseek_gemini

If the file already contains these two columns, the script will reuse them:

    semantic_homogenization_bertscore
    lexical_homogenization_jaccard

Default input path
------------------
    /Users/renwei/Downloads/quantitative_results_bertscore_100_detailed.csv

Default outputs
---------------
    /Users/renwei/Downloads/table_4_1_error_type_homogenization.csv
    /Users/renwei/Downloads/table_4_1_error_type_homogenization.xlsx

Usage
-----
Option 1: Use default paths

    python generate_table_4_1.py

Option 2: Specify your own input file

    python generate_table_4_1.py --input /path/to/quantitative_results_bertscore_100_detailed.csv

Option 3: Specify input and output directory

    python generate_table_4_1.py \
        --input /path/to/quantitative_results_bertscore_100_detailed.csv \
        --output-dir /path/to/output_folder
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import pandas as pd


DEFAULT_INPUT = Path("/Users/renwei/Downloads/quantitative_results_bertscore_100_detailed.csv")

BERTSCORE_PAIR_COLUMNS = [
    "bertscore_gpt_deepseek",
    "bertscore_gpt_gemini",
    "bertscore_deepseek_gemini",
]

JACCARD_PAIR_COLUMNS = [
    "jaccard_gpt_deepseek",
    "jaccard_gpt_gemini",
    "jaccard_deepseek_gemini",
]

SEMANTIC_SCORE_COLUMN = "semantic_homogenization_bertscore"
LEXICAL_SCORE_COLUMN = "lexical_homogenization_jaccard"

# This order matches the order reported in the paper.
ERROR_TYPE_ORDER = [
    "grammar-related error",
    "data description error",
    "idiomaticity or non-standard expression problem",
    "collocation problem",
    "lexical choice error",
    "comparison-related error",
    "cohesion problem",
]

# Optional display labels used in the final paper table.
DISPLAY_LABELS = {
    "grammar-related error": "Grammar-related error",
    "data description error": "Data description error",
    "idiomaticity or non-standard expression problem": "Idiomaticity / non-standard expression",
    "collocation problem": "Collocation problem",
    "lexical choice error": "Lexical choice error",
    "comparison-related error": "Comparison-related error",
    "cohesion problem": "Cohesion problem",
}


def check_required_columns(df: pd.DataFrame, required_columns: Iterable[str]) -> None:
    """Raise a clear error message if required columns are missing."""
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        raise ValueError(
            "The input file is missing required columns:\n"
            f"{missing}\n\n"
            "Available columns are:\n"
            f"{list(df.columns)}"
        )


def normalize_error_type(value: object) -> str:
    """
    Normalize error type labels so that minor capitalization or wording variation
    will not prevent grouping.

    This keeps the script reusable if the input file contains labels such as:
    'Grammar-related error' or 'Idiomaticity / non-standard expression'.
    """
    text = str(value).strip().lower()

    replacements = {
        "grammar-related errors": "grammar-related error",
        "data description errors": "data description error",
        "idiomaticity / non-standard expression": "idiomaticity or non-standard expression problem",
        "idiomaticity/non-standard expression": "idiomaticity or non-standard expression problem",
        "idiomaticity or non-standard expression": "idiomaticity or non-standard expression problem",
        "idiomaticity or non-standard expression problems": "idiomaticity or non-standard expression problem",
        "collocation problems": "collocation problem",
        "lexical choice errors": "lexical choice error",
        "comparison-related errors": "comparison-related error",
        "cohesion problems": "cohesion problem",
    }

    return replacements.get(text, text)


def add_homogenization_scores(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add semantic and lexical homogenization columns if they are not already present.

    Semantic homogenization:
        average BERTScore F1 across the three pairwise model comparisons.

    Lexical homogenization:
        average Jaccard Similarity across the same three pairwise model comparisons.
    """
    df = df.copy()

    if SEMANTIC_SCORE_COLUMN not in df.columns:
        check_required_columns(df, BERTSCORE_PAIR_COLUMNS)
        df[SEMANTIC_SCORE_COLUMN] = df[BERTSCORE_PAIR_COLUMNS].mean(axis=1)

    if LEXICAL_SCORE_COLUMN not in df.columns:
        check_required_columns(df, JACCARD_PAIR_COLUMNS)
        df[LEXICAL_SCORE_COLUMN] = df[JACCARD_PAIR_COLUMNS].mean(axis=1)

    return df


def generate_table_4_1(df: pd.DataFrame) -> pd.DataFrame:
    """Generate Table 4.1 by grouping results by error type."""
    check_required_columns(df, ["unit_id", "error_type"])

    df = add_homogenization_scores(df)
    df["error_type_normalized"] = df["error_type"].apply(normalize_error_type)

    table = (
        df.groupby("error_type_normalized", dropna=False)
        .agg(
            n=("unit_id", "count"),
            Mean_BERTScore_F1=(SEMANTIC_SCORE_COLUMN, "mean"),
            Mean_Jaccard_Similarity=(LEXICAL_SCORE_COLUMN, "mean"),
        )
        .reset_index()
    )

    # Keep only known categories in the intended order, then append any unexpected
    # categories at the end instead of silently dropping them.
    table["error_type_normalized"] = table["error_type_normalized"].astype(str)

    known = table[table["error_type_normalized"].isin(ERROR_TYPE_ORDER)].copy()
    unknown = table[~table["error_type_normalized"].isin(ERROR_TYPE_ORDER)].copy()

    known["sort_order"] = known["error_type_normalized"].apply(ERROR_TYPE_ORDER.index)
    known = known.sort_values("sort_order").drop(columns="sort_order")

    unknown = unknown.sort_values("error_type_normalized")

    table = pd.concat([known, unknown], ignore_index=True)

    # Round to three decimals for paper reporting.
    table["Mean_BERTScore_F1"] = table["Mean_BERTScore_F1"].round(3)
    table["Mean_Jaccard_Similarity"] = table["Mean_Jaccard_Similarity"].round(3)

    # Rename for presentation.
    table["Error Type"] = table["error_type_normalized"].map(DISPLAY_LABELS).fillna(
        table["error_type_normalized"]
    )

    table = table.rename(
        columns={
            "n": "n",
            "Mean_BERTScore_F1": "Mean BERTScore F1",
            "Mean_Jaccard_Similarity": "Mean Jaccard Similarity",
        }
    )

    return table[["Error Type", "n", "Mean BERTScore F1", "Mean Jaccard Similarity"]]


def save_table(table: pd.DataFrame, output_dir: Path) -> tuple[Path, Path]:
    """Save Table 4.1 as CSV and Excel."""
    output_dir.mkdir(parents=True, exist_ok=True)

    output_csv = output_dir / "table_4_1_error_type_homogenization.csv"
    output_excel = output_dir / "table_4_1_error_type_homogenization.xlsx"

    table.to_csv(output_csv, index=False, encoding="utf-8-sig")
    table.to_excel(output_excel, index=False)

    return output_csv, output_excel


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Table 4.1 from detailed BERTScore and Jaccard results."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Path to detailed quantitative results CSV. Default: {DEFAULT_INPUT}",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory for output CSV and Excel files. "
            "Default: the same folder as the input CSV."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    input_path = args.input.expanduser().resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Cannot find input file: {input_path}")

    output_dir = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else input_path.parent
    )

    df = pd.read_csv(input_path)
    table_4_1 = generate_table_4_1(df)
    output_csv, output_excel = save_table(table_4_1, output_dir)

    print("\nTable 4.1 generated successfully.\n")
    print(table_4_1.to_string(index=False))
    print(f"\nSaved CSV file to:   {output_csv}")
    print(f"Saved Excel file to: {output_excel}")

    print(
        "\nNote. n refers to the number of error units in each category. "
        "Mean BERTScore F1 and Mean Jaccard Similarity refer to the average "
        "of the three pairwise model scores for each error unit."
    )


if __name__ == "__main__":
    main()
