#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_table_4_3.py

Purpose
-------
Generate Table 4.3: Pairwise Model Similarity.

This table was generated to examine output homogenization as a relational
property. Since output homogenization refers to convergence among model-generated
revisions, it was measured through pairwise comparisons rather than individual
model-level scores.

Calculation logic
-----------------
Each learner-generated error unit was revised by three LLMs:

    1. GPT-4o-mini
    2. DeepSeek-V3
    3. Gemini Flash

For each error unit, the revision outputs were compared in three model pairs:

    1. GPT-4o-mini vs DeepSeek-V3
    2. GPT-4o-mini vs Gemini Flash
    3. DeepSeek-V3 vs Gemini Flash

For each pair, two similarity metrics were calculated:

    - BERTScore F1: semantic similarity between the two model revisions
    - Jaccard Similarity: lexical overlap between the two model revisions

Table 4.3 reports the mean and standard deviation of these pairwise scores
across the 100 error units.

In the paper, the table note can be written as:

    Note. Pairwise scores were calculated by comparing the revision outputs
    generated by each pair of models for the same error unit. Mean and SD values
    were computed across the 100 error units. Values are rounded to three
    decimal places.

Expected input
--------------
A detailed quantitative results CSV file, normally produced by the full
BERTScore + Jaccard analysis script.

The input file should contain at least the following pairwise score columns:

    bertscore_gpt_deepseek
    bertscore_gpt_gemini
    bertscore_deepseek_gemini
    jaccard_gpt_deepseek
    jaccard_gpt_gemini
    jaccard_deepseek_gemini

Default input path
------------------
    /Users/renwei/Downloads/quantitative_results_bertscore_100_detailed.csv

Default outputs
---------------
    /Users/renwei/Downloads/table_4_3_pairwise_model_similarity.csv
    /Users/renwei/Downloads/table_4_3_pairwise_model_similarity.xlsx
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import pandas as pd


DEFAULT_INPUT = Path("/Users/renwei/Downloads/quantitative_results_bertscore_100_detailed.csv")

PAIRWISE_COLUMNS = {
    "GPT-4o-mini vs DeepSeek-V3": {
        "bertscore": "bertscore_gpt_deepseek",
        "jaccard": "jaccard_gpt_deepseek",
    },
    "GPT-4o-mini vs Gemini Flash": {
        "bertscore": "bertscore_gpt_gemini",
        "jaccard": "jaccard_gpt_gemini",
    },
    "DeepSeek-V3 vs Gemini Flash": {
        "bertscore": "bertscore_deepseek_gemini",
        "jaccard": "jaccard_deepseek_gemini",
    },
}


def check_required_columns(df: pd.DataFrame, required_columns: Iterable[str]) -> None:
    """Raise a clear error message if required columns are missing."""
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        raise ValueError(
            "The input file is missing required columns:\n"
            f"{missing}\n\n"
            "Available columns are:\n"
            f"{list(df.columns)}"
        )


def generate_table_4_3(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate Table 4.3.

    The table reports pairwise model similarity across all error units:
        - Mean BERTScore F1
        - SD of BERTScore F1
        - Mean Jaccard Similarity
        - SD of Jaccard Similarity

    By default, pandas uses sample standard deviation (ddof=1), which is
    appropriate for reporting descriptive statistics for the sample.
    """
    required_columns = []
    for pair_info in PAIRWISE_COLUMNS.values():
        required_columns.append(pair_info["bertscore"])
        required_columns.append(pair_info["jaccard"])

    check_required_columns(df, required_columns)

    rows = []
    for model_pair, pair_info in PAIRWISE_COLUMNS.items():
        bertscore_col = pair_info["bertscore"]
        jaccard_col = pair_info["jaccard"]

        rows.append(
            {
                "Model Pair": model_pair,
                "Mean BERTScore F1": df[bertscore_col].mean(),
                "SD BERTScore F1": df[bertscore_col].std(),
                "Mean Jaccard Similarity": df[jaccard_col].mean(),
                "SD Jaccard Similarity": df[jaccard_col].std(),
            }
        )

    table = pd.DataFrame(rows)

    numeric_columns = [
        "Mean BERTScore F1",
        "SD BERTScore F1",
        "Mean Jaccard Similarity",
        "SD Jaccard Similarity",
    ]
    table[numeric_columns] = table[numeric_columns].round(3)

    return table


def save_table(table: pd.DataFrame, output_dir: Path) -> tuple[Path, Path]:
    """Save Table 4.3 as CSV and Excel."""
    output_dir.mkdir(parents=True, exist_ok=True)

    output_csv = output_dir / "table_4_3_pairwise_model_similarity.csv"
    output_excel = output_dir / "table_4_3_pairwise_model_similarity.xlsx"

    table.to_csv(output_csv, index=False, encoding="utf-8-sig")
    table.to_excel(output_excel, index=False)

    return output_csv, output_excel


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Table 4.3 from detailed pairwise BERTScore and Jaccard results."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Path to detailed quantitative results CSV. Default: {DEFAULT_INPUT}",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory for output CSV and Excel files. "
            "Default: the same folder as the input CSV."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    input_path = args.input.expanduser().resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Cannot find input file: {input_path}")

    output_dir = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else input_path.parent
    )

    df = pd.read_csv(input_path)
    table_4_3 = generate_table_4_3(df)
    output_csv, output_excel = save_table(table_4_3, output_dir)

    print("\nTable 4.3 generated successfully.\n")
    print(table_4_3.to_string(index=False))
    print(f"\nSaved CSV file to:   {output_csv}")
    print(f"Saved Excel file to: {output_excel}")

    print(
        "\nNote. Pairwise scores were calculated by comparing the revision outputs "
        "generated by each pair of models for the same error unit. Mean and SD "
        "values were computed across the error units. Values are rounded to "
        "three decimal places."
    )


if __name__ == "__main__":
    main()
